name: Flutter Workflow
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.10.0'
          channel: 'stable'
      - name: Install Java
        uses: actions/setup-java@v1
        with:
          java-version: '2.5.3'
#      - name: Install dependencies
#        run: flutter pub get






