name: Flutter Workflow
on: [push, pull_request]
jobs:
  build1:
    name: on Android
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.9'
          channel: 'stable'
      - name: Install Java
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - run: flutter --version
      - run: |
          cd example_app
          flutter packages get
      - run: |
          cd example_app
          flutter test
      - run:  |
          cd example_app
          flutter build apk
      - run: |
          cd example_app
          flutter build appbundle
  build2:
    name: on IOS
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.9'
          channel: 'stable'

      - run: flutter --version
      - run: |
          cd example_app
          flutter packages get
      - run: |
          cd example_app
          flutter test
      - run: |
          cd example_app
          flutter build ios --release --no-codesign
      - run: |
          cd example_app
          flutter build appbundle








